# Generated by Django 2.0.2 on 2018-04-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0002_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=' DEFAULT', max_length=5000, upload_to=''),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default=' DEFAULT', max_length=50),
        ),
    ]
