# Generated by Django 2.0.2 on 2018-04-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0003_auto_20180412_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=5000, upload_to='media/%s'),
        ),
    ]
