# Generated by Django 2.0.2 on 2018-04-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0004_auto_20180412_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(default='Choose file', max_length=5000, upload_to='media/%s'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='Upload your file', max_length=50),
        ),
    ]
