# Generated by Django 2.0.4 on 2018-04-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0008_auto_20180417_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(default='Choose file', max_length=5000, upload_to='media/%s'),
        ),
    ]
