# Generated by Django 2.0.4 on 2018-04-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0009_auto_20180418_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
