# Generated by Django 2.0.4 on 2018-04-19 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0011_auto_20180418_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
