# Generated by Django 2.0.4 on 2018-04-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0012_remove_document_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
