# Generated by Django 2.0.4 on 2018-04-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0016_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
