# Generated by Django 2.0.4 on 2018-04-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0020_auto_20180421_0029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
