# Generated by Django 2.0.4 on 2018-04-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0023_document_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
