# Generated by Django 2.0.4 on 2018-04-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0026_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(upload_to='')),
                ('file2', models.FileField(upload_to='')),
            ],
        ),
    ]
