# Generated by Django 2.0.4 on 2018-04-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0027_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
