# Generated by Django 2.0.4 on 2018-07-04 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0028_auto_20180429_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='reg',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plagtrace.Register'),
        ),
    ]
