# Generated by Django 2.0.4 on 2018-07-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0029_auto_20180704_0404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Signup',
        ),
    ]
