# Generated by Django 2.0.4 on 2018-07-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0030_auto_20180704_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='reg',
        ),
    ]
