# Generated by Django 2.0.4 on 2018-07-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0031_remove_contact_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reg',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plagtrace.Signup'),
        ),
    ]
