# Generated by Django 2.0.4 on 2018-07-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagtrace', '0032_contact_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='reg',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
